name: ORT

on: 
  workflow_dispatch:

jobs:
  ort_scan:
    runs-on: ubuntu-latest
    name: Scan project with ORT
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          path: project
      - id: foo
        uses: jandersssonse/ort-ci-github-action@main
        with:
          sw-name: 'Gradle Versions'
