name: ORT Scan
on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: ORT Scan Dependendencies

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project

#     - name: Checkout scancode results repo
#       uses: actions/checkout@v3
#       with:
#         repository: janderssonse/scancode-results
#         path: scancoderesults

      - name: ORT CI Action
        id: ort-ci-action
        uses: janderssonse/ort-ci-action@60a355cc40b9c1539c51356af1e6d46fa1933ada
        with:
          ort_disable_scanner: true
          ort_disable_downloader: true
          ort_disable_evaluator: true
          ort_disable_advisor: false
          ort_opts: -Xmx5120m
        
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./project/ort-results
