name: ORT Scan
on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: ORT Scan Dependendencies

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project

#     - name: Checkout scancode results repo
#       uses: actions/checkout@v3
#       with:
#         repository: janderssonse/scancode-results
#         path: scancoderesults
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
         registry: "ghcr.io"
         username: ${{ github.actor}}
         password: ${{ secrets.ACTIONCI }}

      - name: ORT CI Action
        id: ort-ci-action
        uses: janderssonse/ort-ci-action@043e9f22fa0d09ec59f229fc578dbb22b6e2ab09
        with:
          registry_host: "ghcr.io"
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.ACTIONCI }}

          ort_disable_scanner: true
          ort_disable_downloader: true
          ort_disable_evaluator: true
          ort_disable_advisor: false
          ort_opts: -Xmx5120m
        
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./project/ort-results
