on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: Analyse with ORT

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout scancode results repo
        uses: actions/checkout@v3
        with:
          repository: janderssonse/scancode-results
          path: scancode

      - name: Ort action analyse step
        id: ort-action
        uses: janderssonse/ort-action@8193d594b84c7813f7d37617313c1b827adcd5d8
        with:
          scan: true
          ort_log_level: info
          ort_conf: ort.conf
        
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./reports

