name: Ort Report Action
on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: Analyse with ORT

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project

#     - name: Checkout scancode results repo
#       uses: actions/checkout@v3
#       with:
#         repository: janderssonse/scancode-results
#         path: scancoderesults

      - name: Ort action analyse step
        id: ort-action
        uses: janderssonse/ort-ci-action@70c1ad0cdf23a8ae9294ce7e980a16ad6db7757d
        with:
          ort_disable_scanner: false
          ort_disable_downloader: true
          ort_disable_evaluator: true
          ort_disable_advisor: false
          ort_config_file: ''
          ort_log_level: info
          ort_opts: -Xmx5120m
        
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./project/ort-results
