name: Ort Report Action
on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: Analyse with ORT

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project

#     - name: Checkout scancode results repo
#       uses: actions/checkout@v3
#       with:
#         repository: janderssonse/scancode-results
#         path: scancode

      - name: Ort action analyse step
        id: ort-action
        uses: janderssonse/ort-action@8e784a01543bef43f862f038f5fa3d5ffd811ebe
        with:
          ort_disable_scanner: true
          ort_cli_config_template: /tmp/ort.conf
          ort_disable_downloader: true
          ort_disable_evaluator: true
          ort_disable_advisor: false
          ort_log_level: info
        
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./project/ort-results
