on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: Analyse with ORT

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Ort action analyse step
        id: ort-action
        uses: janderssonse/ort-action@471a3aa574dbe93569ccb32f5ec0b3786c236ef5
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./reports

