on: [push]

jobs:
  ort_report_job:
    runs-on: ubuntu-latest
    name: Analyse with ORT

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout scancode results repo
        uses: actions/checkout@v3
        with:
          repository: janderssonse/scancode-results
          path: scancode

      - name: Ort action analyse step
        id: ort-action
        uses: janderssonse/ort-action@c9e65c1e4fbe698c67bd5e4b6886b7a8a1d83aa1
        with:
          scan: true
          ort_log_level: debug
          ort_conf: ort.conf
        
       
      - name: ort-action-artifacts
        uses: actions/upload-artifact@v2
        with:
            name: analysis
            path: ./reports

